name: CI

on:
  pull_request:
    branches: [ "main" ]
  push: {}

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Create virtuel environment
        run: uv venv

      - name: Install project dependancies
        run: uv pip install -e ".[dev]"

      - name: Run Lint check
        run: uv run ruff check .

      - name: Run Format check
        run: uv run ruff format --check .

      - name: Run Unit Tests
        run: uv run pytest
